PojistovnaWebApp/Controllers/PojisteneOsobyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PojistovnaWebApp.Data;
using PojistovnaWebApp.Models;

namespace PojistovnaWebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class PojisteneOsobyController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PojisteneOsobyController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PojisteneOsoby
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
              return View(await _context.PojisteneOsoby.ToListAsync());
        }

        // GET: PojisteneOsoby/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PojisteneOsoby == null)
            {
                return NotFound();
            }

            var pojisteneOsoby = await _context.PojisteneOsoby
                .FirstOrDefaultAsync(m => m.IdOsoby == id);
            if (pojisteneOsoby == null)
            {
                return NotFound();
            }

            return View(pojisteneOsoby);
        }

        // GET: PojisteneOsoby/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PojisteneOsoby/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdOsoby,Jmeno,Prijmeni,Email,Telefon,Ulice,Mesto,Psc")] PojisteneOsoby pojisteneOsoby)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pojisteneOsoby);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pojisteneOsoby);
        }

        // GET: PojisteneOsoby/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PojisteneOsoby == null)
            {
                return NotFound();
            }

            var pojisteneOsoby = await _context.PojisteneOsoby.FindAsync(id);
            if (pojisteneOsoby == null)
            {
                return NotFound();
            }
            return View(pojisteneOsoby);
        }

        // POST: PojisteneOsoby/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdOsoby,Jmeno,Prijmeni,Email,Telefon,Ulice,Mesto,Psc")] PojisteneOsoby pojisteneOsoby)
        {
            if (id != pojisteneOsoby.IdOsoby)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pojisteneOsoby);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PojisteneOsobyExists(pojisteneOsoby.IdOsoby))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pojisteneOsoby);
        }

        // GET: PojisteneOsoby/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PojisteneOsoby == null)
            {
                return NotFound();
            }

            var pojisteneOsoby = await _context.PojisteneOsoby
                .FirstOrDefaultAsync(m => m.IdOsoby == id);
            if (pojisteneOsoby == null)
            {
                return NotFound();
            }

            return View(pojisteneOsoby);
        }

        // POST: PojisteneOsoby/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PojisteneOsoby == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PojisteneOsoby'  is null.");
            }
            var pojisteneOsoby = await _context.PojisteneOsoby.FindAsync(id);
            if (pojisteneOsoby != null)
            {
                _context.PojisteneOsoby.Remove(pojisteneOsoby);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PojisteneOsobyExists(int id)
        {
          return _context.PojisteneOsoby.Any(e => e.IdOsoby == id);
        }
    }
}

PojistovnaWebApp/Controllers/SeznamPojisteniController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PojistovnaWebApp.Data;
using PojistovnaWebApp.Models;

namespace PojistovnaWebApp.Controllers
{
    public class SeznamPojisteniController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SeznamPojisteniController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SeznamPojisteni
        public async Task<IActionResult> Index()
        {
              return View(await _context.SeznamPojisteni.ToListAsync());
        }

        // GET: SeznamPojisteni/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SeznamPojisteni == null)
            {
                return NotFound();
            }

            var seznamPojisteni = await _context.SeznamPojisteni
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seznamPojisteni == null)
            {
                return NotFound();
            }

            return View(seznamPojisteni);
        }

        // GET: SeznamPojisteni/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SeznamPojisteni/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NazevPojisteni,Perex,Popis")] SeznamPojisteni seznamPojisteni)
        {
            if (ModelState.IsValid)
            {
                _context.Add(seznamPojisteni);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(seznamPojisteni);
        }

        // GET: SeznamPojisteni/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SeznamPojisteni == null)
            {
                return NotFound();
            }

            var seznamPojisteni = await _context.SeznamPojisteni.FindAsync(id);
            if (seznamPojisteni == null)
            {
                return NotFound();
            }
            return View(seznamPojisteni);
        }

        // POST: SeznamPojisteni/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NazevPojisteni,Perex,Popis, PojisteniOd, PojisteniDo, Cena")] SeznamPojisteni seznamPojisteni)
        {
            if (id != seznamPojisteni.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seznamPojisteni);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SeznamPojisteniExists(seznamPojisteni.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(seznamPojisteni);
        }

        // GET: SeznamPojisteni/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SeznamPojisteni == null)
            {
                return NotFound();
            }

            var seznamPojisteni = await _context.SeznamPojisteni
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seznamPojisteni == null)
            {
                return NotFound();
            }

            return View(seznamPojisteni);
        }

        // POST: SeznamPojisteni/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SeznamPojisteni == null)
            {
                return Problem("Entity set 'ApplicationDbContext.SeznamPojisteni'  is null.");
            }
            var seznamPojisteni = await _context.SeznamPojisteni.FindAsync(id);
            if (seznamPojisteni != null)
            {
                _context.SeznamPojisteni.Remove(seznamPojisteni);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SeznamPojisteniExists(int id)
        {
          return _context.SeznamPojisteni.Any(e => e.Id == id);
        }
    }
}

PojistovnaWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PojistovnaWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PojistovnaWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="bg-dark border-bottom">
        <header class="container">
            <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark">
                <button class="navbar-toggler ml-auto collapsed" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="container-fluid ">
                        <div class="navbar-collapse d-flex justify-content-between flex-wrap">
					        <div class="d-flex align-items-center justify-content-center navbar-brand">
                                <div class="text-center">
                                   <h1 class="mb-0" style="font-size: 115%">POJIŠŤOVNA</h1>
                                   <h2 class="mt-0">WEB APP</h2>
                                </div>
                            </div>
                            <ul class="navbar-nav mr-auto d-flex align-items-center">
							    <li class="nav-item px-2  navbar-underline"><a class="nav-link text-light" asp-controller="Home" asp-action="Index">DOMŮ<span class="sr-only"></span></a></li>
							    <li class="nav-item px-2  navbar-underline"><a class="nav-link text-light" asp-controller="PojisteneOsoby" asp-action="Index">POJIŠTĚNÉ OSOBY<span class="sr-only"></span></a></li>
							    <li class="nav-item px-2  navbar-underline"><a class="nav-link text-light" asp-controller="SeznamPojisteni" asp-action="index">POJIŠTĚNÍ<span class="sr-only"></span></a></li>
                                <li class="nav-item px-2  navbar-underline"><a class="nav-link text-light" asp-controller="PojistneUdalosti" asp-action="index">POJISTNÁ UDÁLOST<span class="sr-only"></span></a></li>
							    <li class="nav-item px-2  navbar-underline"><a class="nav-link text-light" asp-controller="Home" asp-action="Kontakt">KONTAKT<span class="sr-only"></span></a></li>
                                <li class="nav-item mx-3  nav-item-divider"></li>
                                @if (SignInManager.IsSignedIn(User))
                                {
                                <li class="nav-item px-2  navbar-underline">
                                    <form class="form-inline" asp-area="" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button type="submit" class="nav-link btn btn-link text-light">ODHLÁŠENÍ</button>
                                    </form>
                                </li>
                                }
                                else
                                {
                                <li class="nav-item  px-2 navbar-underline"><a class="nav-link text-light" asp-controller="Account" asp-action="Register">REGISTROVAT</a></li>
                                <li class="nav-item px-2 d-none d-lg-block text-light">|</li>
                                <li class="nav-item px-2  navbar-underline"><a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">PŘIHLÁŠENÍ</a></li>
                                }
                            </ul>
						</div>
                    </div>
				</nav>
    </header>
    </div>
    <div class="container mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bg-dark text-white mt-5 fixed-bottom">
		<div class="container py-3 text-center col-md-6">
            <p>Vytvořil &copy;HoSTR @DateTime.Now.Year</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>